// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CardLinkMenu: typeof import('./src/components/card-link-menu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListCompaniesPanel: typeof import('./src/components/ListCompaniesPanel.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    SelectInput: typeof import('./src/components/SelectInput.vue')['default']
    TextInput: typeof import('./src/components/TextInput.vue')['default']
  }
}

export { }
